spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reports
logging:
  level:
     com.jorge.cycletimecrawler.integration.FreedomIntegration: DEBUG
feign:
 client:
  default:
    logging-level: HEADERS